###
### Retrieve a token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "usertest@example.com",
  "password": "usertest"
}

> {%
client.global.set("token", response.body.token);
%}


###
### Invalidate the token
###
DELETE {{protocol}}{{host}}:{{port}}/auth
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
