###
### Retrieve a user token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "usertest@example.com",
  "password": "usertest"
}

> {%
client.global.set("user_token", response.body.token);
%}

###
### Retrieve a admin token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/tokens
Content-Type: application/json
Accept: application/json

{
  "email": "admintest@example.com",
  "password": "admintest"
}

> {%
client.global.set("admin_token", response.body.token);
%}

