### Testing to get the list of all bids for specific book with isbn 9780451203581

GET http://localhost:3000/books/9780451203581/bids

> {%
client.test(
    "Testing to get the list of all bids for specific book with isbn 9780451203581",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}

### Testing to post a new bid for specific book with isbn 9780451203581 with admin

POST http://localhost:3000//books/9780451203581/bids
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "id": 3,
  "username": "admintest",
  "amount": 400,
  "date": "04.11.2023 20:29"
}

> {%
client.test(
    "Testing to post a new bid for specific book with isbn 9780451203581 with admin",
    function() {
        client.assert(response.status === 201, "Response status is not 201");
        client.assert(response.body.id === 3, "Expected id - 3")
        client.assert(response.body.amount >= 0, "The amount must be positive number");
    }
);
%}

### Testing to post a new bid for specific book with isbn 9780451203581 with user

POST http://localhost:3000//books/9780451203581/bids
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
  "id": 4,
  "username": "usertest",
  "amount": 500,
  "date": "04.11.2023 21:29"
}

> {%
client.test(
    "Testing to post a new bid for specific book with isbn 9780451203581 with user",
    function() {
        client.assert(response.status === 201, "Response status is not 201");
        client.assert(response.body.id === 4, "Expected id - 4")
        client.assert(response.body.amount >= 0, "The amount must be positive number");
    }
);
%}