### Testing to get the list of all users

GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{admin_token}}

> {%
client.test(
    "Testing to get the list of all users",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}

### Testing to post a new user

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "usertestfromtests@example.com",
  "password": "usertestfromtests"
}


> {%
client.test(
    "Testing to post a new user",
    function() {
        client.assert(response.status === 201, "Response status is not 201");
    }
);
%}

### Testing to post a new user with no password (BAD WEATHER)

POST http://localhost:3000/users
Content-Type: application/json

{
  "password": "usertestfromtests"
}


> {%
client.test(
    "Testing to post a new user with no password (BAD WEATHER)",
    function() {
        client.assert(response.status === 400, "Response status is not 400");
    }
);
%}

### Testing to post a new user with no email (BAD WEATHER)

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "usertestfromtests@example.com"
}


> {%
client.test(
    "Testing to post a new user with no email (BAD WEATHER)",
    function() {
        client.assert(response.status === 400, "Response status is not 400");
    }
);
%}

### Testing to delete user with id 3

DELETE http://localhost:3000/users/3
Content-Type: application/json
Authorization: Bearer {{admin_token}}

> {%
client.test(
    "Testing to delete user with id 3",
    function() {
        client.assert(response.status === 200, "Response status is not 200");
    }
);
%}